version: '3'

services:
  mazeapi:
    image: mazeapi
    networks:
      - overlay
    ports:
      - "49907:80"

  mazesolverapi:
    image: mazesolverapi
    networks:
      - overlay
    ports:
      - "52059:80"


  mazeclient:
    image: mazeclient
    networks:
      - overlay
    ports:
      - "80:80"
    
networks:
  overlay:
