version: '3'

services:
  mazeapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  mazesolverapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
