//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazeLibTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MazeLibTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;width&quot;:5,&quot;height&quot;:5,&quot;cells&quot;:[[{&quot;start&quot;:true,&quot;goal&quot;:false,&quot;row&quot;:0,&quot;col&quot;:0,&quot;coordinates&quot;:{&quot;row&quot;:0,&quot;col&quot;:0},&quot;up&quot;:false,&quot;right&quot;:false,&quot;down&quot;:true,&quot;left&quot;:false},{&quot;start&quot;:false,&quot;goal&quot;:false,&quot;row&quot;:0,&quot;col&quot;:1,&quot;coordinates&quot;:{&quot;row&quot;:0,&quot;col&quot;:1},&quot;up&quot;:false,&quot;right&quot;:true,&quot;down&quot;:false,&quot;left&quot;:false},{&quot;start&quot;:false,&quot;goal&quot;:false,&quot;row&quot;:0,&quot;col&quot;:2,&quot;coordinates&quot;:{&quot;row&quot;:0,&quot;col&quot;:2},&quot;up&quot;:false,&quot;right&quot;:true,&quot;down&quot;:true,&quot;left&quot;:true},{&quot;start&quot;:false,&quot;goal&quot;:false,&quot;row&quot;:0,&quot;col&quot;:3,&quot;coordinates&quot;:{&quot;row&quot;:0,&quot;col&quot;:3},&quot;up&quot;:false,&quot;right&quot;:true,&quot;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FiveByFiveMazeJson {
            get {
                return ResourceManager.GetString("FiveByFiveMazeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;width&quot;:6,&quot;height&quot;:6,&quot;cells&quot;:[[{&quot;start&quot;:true,&quot;goal&quot;:false,&quot;row&quot;:0,&quot;col&quot;:0,&quot;coordinates&quot;:{&quot;row&quot;:0,&quot;col&quot;:0},&quot;up&quot;:false,&quot;right&quot;:true,&quot;down&quot;:false,&quot;left&quot;:false},{&quot;start&quot;:false,&quot;goal&quot;:false,&quot;row&quot;:0,&quot;col&quot;:1,&quot;coordinates&quot;:{&quot;row&quot;:0,&quot;col&quot;:1},&quot;up&quot;:false,&quot;right&quot;:true,&quot;down&quot;:false,&quot;left&quot;:true},{&quot;start&quot;:false,&quot;goal&quot;:false,&quot;row&quot;:0,&quot;col&quot;:2,&quot;coordinates&quot;:{&quot;row&quot;:0,&quot;col&quot;:2},&quot;up&quot;:false,&quot;right&quot;:false,&quot;down&quot;:true,&quot;left&quot;:true},{&quot;start&quot;:false,&quot;goal&quot;:false,&quot;row&quot;:0,&quot;col&quot;:3,&quot;coordinates&quot;:{&quot;row&quot;:0,&quot;col&quot;:3},&quot;up&quot;:false,&quot;right&quot;:true,&quot;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SixBySixMazeJson {
            get {
                return ResourceManager.GetString("SixBySixMazeJson", resourceCulture);
            }
        }
    }
}
